Aspose/releases.aspose.com

content/en/tex/java/release-notes/2021/_index.md, content/en/tex/java/release-notes/2021/aspose-tex-for-java-21-11-release-notes.md, content/en/tex/java/release-notes/2021/aspose-tex-for-java-21-4-release-notes.md, content/en/tex/java/release-notes/2021/aspose-tex-for-java-21-8-release-notes.md, content/en/tex/java/release-notes/2021/aspose-tex-for-java-21-9-release-notes.md, content/en/tex/java/release-notes/2022/_index.md, content/en/tex/java/release-notes/2022/aspose-tex-for-java-22-10-release-notes.md, content/en/tex/java/release-notes/2022/aspose-tex-for-java-22-11-release-notes.md, content/en/tex/java/release-notes/2022/aspose-tex-for-java-22-12-release-notes.md, content/en/tex/java/release-notes/2022/aspose-tex-for-java-22-2-release-notes.md, content/en/tex/java/release-notes/2022/aspose-tex-for-java-22-3-release-notes.md, content/en/tex/java/release-notes/2022/aspose-tex-for-java-22-4-release-notes.md, content/en/tex/java/release-notes/2022/aspose-tex-for-java-22-6-release-notes.md, content/en/tex/java/release-notes/2022/aspose-tex-for-java-22-8-release-notes.md, content/en/tex/java/release-notes/2023/_index.md, content/en/tex/java/release-notes/2023/aspose-tex-for-java-23-2-release-notes.md, content/en/tex/java/release-notes/2023/aspose-tex-for-java-23-4-release-notes.md, content/en/tex/java/release-notes/_index.md
Aspose.TeX for JAVA - Release Note Migration v1.0
=> Aspose.TeX for JAVA - Release Note Migration v1.0

content/en/html/net/release-notes/2023/aspose-html-for-net-23-8-release-notes.md
=> Prepared the aspose-html-for-net-23-8-release-notes.md

content/en/html/net/release-notes/2023/aspose-html-for-net-23-9-release-notes.md
=> Updated the release notes

content/de/page/net/new-releases/aspose.page-for-.net-23.9-(dlls-and-docs).md, content/el/page/net/new-releases/aspose.page-for-.net-23.9-(dlls-and-docs).md, content/en/page/net/new-releases/aspose.page-for-.net-23.9-(dlls-and-docs).md, content/en/page/net/release-notes/aspose.page-for-.net-23.8-(dlls-and-docs).md, content/en/page/net/release-notes/aspose.page-for-.net-23.8.md, content/es/page/net/new-releases/aspose.page-for-.net-23.9-(dlls-and-docs).md, content/fr/page/net/new-releases/aspose.page-for-.net-23.9-(dlls-and-docs).md, content/id/page/net/new-releases/aspose.page-for-.net-23.9-(dlls-and-docs).md, content/ja/page/net/new-releases/aspose.page-for-.net-23.9-(dlls-and-docs).md, content/pt/page/net/new-releases/aspose.page-for-.net-23.9-(dlls-and-docs).md, content/ru/page/net/new-releases/aspose.page-for-.net-23.9-(dlls-and-docs).md, content/tr/page/net/new-releases/aspose.page-for-.net-23.9-(dlls-and-docs).md, content/zh/page/net/new-releases/aspose.page-for-.net-23.9-(dlls-and-docs).md
=> sync with main

content/en/html/net/release-notes/2023/aspose-html-for-net-23-10-release-notes.md
Added the Aspose.HTML.Net 23.10 release notes.
=> Added the Aspose.HTML.Net 23.10 release notes.

content/en/slides/androidjava/release-notes/2023/aspose-slides-for-android-via-java-23-10-release-notes.md, content/en/slides/java/release-notes/2023/aspose-slides-for-java-23-10-release-notes.md, content/en/slides/nodejs-java/release-notes/2023/aspose-slides-for-nodejs-via-java-23-10-release-notes.md, content/en/slides/php-java/release-notes/2023/aspose-slides-for-php-via-java-23-10-release-notes.md
Aspose.Slides for Java/JasperReports/Android/PHP/Node.js 23.10 Release Notes
=> Aspose.Slides for Java/JasperReports/Android/PHP/Node.js 23.10 Release Notes

content/en/html/net/release-notes/2023/aspose-html-for-net-23-11-release-notes.md
Prepared the Aspose.HTML.Net 23.11 release notes.
=> Prepared the Aspose.HTML.Net 23.11 release notes.

content/en/slides/androidjava/release-notes/2023/aspose-slides-for-android-via-java-23-12-release-notes.md, content/en/slides/jasperreport/release-notes/2023/aspose-slides-for-jasper-reports-23-12-release-notes.md, content/en/slides/java/release-notes/2023/aspose-slides-for-java-23-12-release-notes.md, content/en/slides/nodejs-java/release-notes/2023/aspose-slides-for-nodejs-via-java-23-12-release-notes.md, content/en/slides/php-java/release-notes/2023/aspose-slides-for-php-via-java-23-12-release-notes.md
Aspose.Slides for Java/JasperReports/Android/PHP/NodeJS 23.12 Release Notes
=> Aspose.Slides for Java/JasperReports/Android/PHP/NodeJS 23.12 Release Notes

content/en/html/net/release-notes/2024/_index.md, content/en/html/net/release-notes/2024/aspose-html-for-net-24-1-release-notes.md
Prepared the Aspose.HTML.Net 24.1 release notes
=> Prepared the Aspose.HTML.Net 24.1 release notes

content/en/slides/androidjava/release-notes/2024/aspose-slides-for-android-via-java-24-1-release-notes.md
Added missed issues to release notes of Aspose.Slides for Node.js via Java 24.1
=> Added missed issues to release notes of Aspose.Slides for Node.js via Java 24.1

content/en/pdf/net/release-notes/2024/aspose-pdf-for-net-24-02-release-notes.md
Add Aspose.PDF for .NET 24.2 release notes
=> Add Aspose.PDF for .NET 24.2 release notes

content/en/slides/androidjava/release-notes/2024/aspose-slides-for-android-via-java-24-2-release-notes.md, content/en/slides/java/release-notes/2024/aspose-slides-for-java-24-2-release-notes.md, content/en/slides/nodejs-java/release-notes/2024/aspose-slides-for-nodejs-via-java-24-2-release-notes.md, content/en/slides/php-java/release-notes/2024/aspose-slides-for-php-via-java-24-2-release-notes.md
Aspose.Slides for Java/JasperReports/Android/PHP/NodeJS 24.2 Release Notes
=> Aspose.Slides for Java/JasperReports/Android/PHP/NodeJS 24.2 Release Notes

content/en/html/net/release-notes/2024/aspose-html-for-net-24-2-release-notes.md
Updated the release notes for Aspose.HTML.Net 24.2
=> Updated the release notes for Aspose.HTML.Net 24.2

content/en/html/net/release-notes/2024/aspose-html-for-net-24-2-release-notes.md
Prepared the release notes Aspose.HTML.Net 24.2
=> Prepared the release notes Aspose.HTML.Net 24.2

content/en/pdf/net/release-notes/2024/aspose-pdf-for-net-24-03-release-notes.md
Add Aspose.PDF for .NET 24.3 release notes
=> Add Aspose.PDF for .NET 24.3 release notes

content/en/html/net/release-notes/2024/aspose-html-for-net-24-4-release-notes.md
Prepared the release notes Aspose.HTML.Net 24.4
=> Prepared the release notes Aspose.HTML.Net 24.4

content/en/slides/androidjava/release-notes/2024/aspose-slides-for-android-via-java-24-4-release-notes.md, content/en/slides/java/release-notes/2024/aspose-slides-for-java-24-4-release-notes.md, content/en/slides/nodejs-java/release-notes/2024/aspose-slides-for-nodejs-via-java-24-4-release-notes.md, content/en/slides/php-java/release-notes/2024/aspose-slides-for-php-via-java-24-4-release-notes.md, content/en/slides/python-java/release-notes/2024/aspose-slides-for-python-via-java-24-3-release-notes.md, content/en/slides/python-java/release-notes/2024/aspose-slides-for-python-via-java-24-4-release-notes.md
Aspose.Slides for Java/JasperReports/Android/PHP/Node.js/Python 24.4 Release Notes
=> Aspose.Slides for Java/JasperReports/Android/PHP/Node.js/Python 24.4 Release Notes

content/en/drawing/java/release-notes/2024/aspose-drawing-for-java-24-3-release-notes.md
corrected weight of 24.3 release
=> Lemeshkov#drawingjava 113 release 24.4

content/en/pdf/net/release-notes/2024/aspose-pdf-for-net-24-05-release-notes.md
Add Aspose.PDF for .NET 24.5 release notes
=> Add Aspose.PDF for .NET 24.5 release notes

content/en/pdf/net/release-notes/2024/aspose-pdf-for-net-24-05-1-release-notes.md
Add Aspose.PDF for .NET 24.5.1 release notes
=> Add Aspose.PDF for .NET 24.5.1 release notes

content/en/pdf/net/release-notes/2024/aspose-pdf-for-net-24-06-release-notes.md
Add Aspose.PDF for .NET 24.6 release notes
=> Add Aspose.PDF for .NET 24.6 release notes

content/en/html/python-net/_index.md
=> Fixed icon url

content/en/html/net/release-notes/2024/aspose-html-for-net-24-6-release-notes.md, releases.aspose.com.redirects.txt
Added the redirects for aspose-svg-python-via-dotnet-24-6-release-notes
=> Prepared the aspose-html-for-net-24-6-release-notes.md

content/en/html/python-net/release-notes/_index.md
Added content/en/html/python-net/release-notes/_index.md
=> Added content/en/html/python-net/release-notes/_index.md

content/en/pdf/net/release-notes/2024/aspose-pdf-for-net-24-07-release-notes.md
Add Aspose.PDF for .NET 24.7 release notes
=> Add Aspose.PDF for .NET 24.7 release notes

content/en/slides/androidjava/release-notes/2024/aspose-slides-for-android-via-java-24-7-release-notes.md, content/en/slides/java/release-notes/2024/aspose-slides-for-java-24-7-release-notes.md, content/en/slides/nodejs-java/release-notes/2024/aspose-slides-for-nodejs-via-java-24-7-release-notes.md, content/en/slides/php-java/release-notes/2024/aspose-slides-for-php-via-java-24-7-release-notes.md
Aspose.Slides for Java/JasperReports/Android/PHP/Node.js/Python 24.7 Release Notes
=> Aspose.Slides for Java/JasperReports/Android/PHP/Node.js/Python 24.7 Release Notes

content/en/barcode/net/_index.md, content/en/barcode/net/release-notes/2024/aspose-barcode-for-net-24-7-release-notes.md, content/en/barcode/reportingservices/_index.md, content/en/barcode/reportingservices/release-notes/2024/aspose-barcode-for-reporting-services-24-7-release-notes.md
aspose-barcode-for-reporting-services-24-7-release-notes
=> aspose-barcode-for-net-24-6-release-notes

content/en/html/net/release-notes/2024/aspose-html-for-net-24-7-release-notes.md
Prepared the release notes for Aspose.Html.Net 24.7
=> Prepared the release notes for Aspose.Html.Net 24.7

content/en/html/python-net/release-notes/2024/aspose-html-for-python-via-dotnet-24-7-release-notes.md
Prepared the 24.7 Aspose.HTML for Python via NET release notes.
=> Prepared the 24.7 Aspose.HTML for Python via NET release notes.

content/en/slides/androidjava/release-notes/2024/aspose-slides-for-android-via-java-24-8-release-notes.md, content/en/slides/java/release-notes/2024/aspose-slides-for-java-24-8-release-notes.md, content/en/slides/nodejs-java/release-notes/2024/aspose-slides-for-nodejs-via-java-24-8-release-notes.md, content/en/slides/php-java/release-notes/2024/aspose-slides-for-php-via-java-24-8-release-notes.md
Aspose.Slides for Java/JasperReports/Android/PHP/Node.js/Python 24.8 Release Notes
=> Aspose.Slides for Java/JasperReports/Android/PHP/Node.js/Python 24.8 Release Notes

content/en/slides/java/release-notes/2024/aspose-slides-for-java-24-8-release-notes.md
Added the missing issue in Aspose.Slides for Java 24.8 release notes
=> Added the missing issue in Aspose.Slides for Java 24.8 

content/en/pdf/net/release-notes/2024/aspose-pdf-for-net-24-08-release-notes.md
Add Aspose.PDF for .NET 24.8 release notes
=> Add Aspose.PDF for .NET 24.8 release notes

content/en/email/cpp/release-notes/2024/aspose-email-for-cpp-24-8-release-notes.md, content/en/email/pythonnet/release-notes/2024/aspose-email-for-python-via-net-24-8-release-notes.md
RN for 24.8 Aspose.Email for Python via .NET
=> RN for Aspose.Email for C++ 24.8

content/en/html/net/release-notes/2024/aspose-html-for-net-24-8-release-notes.md
Added the Aspose.HTML for .NET  24. 8 release notes
=> Added the Aspose.HTML for .NET  24. 8 release notes

content/en/pdf/net/release-notes/2024/aspose-pdf-for-net-24-09-release-notes.md
Add Aspose.PDF for .NET 24.9 release notes
=> Add Aspose.PDF for .NET 24.9 release notes

content/en/slides/androidjava/release-notes/2024/aspose-slides-for-android-via-java-24-9-release-notes.md, content/en/slides/java/release-notes/2024/aspose-slides-for-java-24-9-release-notes.md, content/en/slides/nodejs-java/release-notes/2024/aspose-slides-for-nodejs-via-java-24-9-release-notes.md
Aspose.Slides for Java/Android/Node.js 24.9 Release Notes
=> Aspose.Slides for Java/JasperReports/Android/PHP/Node.js/Python 24.9 Release Notes

content/en/pdf/net/release-notes/2024/aspose-pdf-for-net-24-10-release-notes.md
Add Aspose.PDF for .NET 24.10 release notes
=> Add Aspose.PDF for .NET 24.10 release notes

content/en/slides/java/release-notes/2024/aspose-slides-for-java-24-10-release-notes.md, content/en/slides/nodejs-java/release-notes/2024/aspose-slides-for-nodejs-via-java-24-10-release-notes.md
Aspose.Slides for Java/JasperReports/Android/PHP/Node.js/Python 24.10 Release Notes
=> Aspose.Slides for Java/JasperReports/Android/PHP/Node.js/Python 24.10 Release Notes

content/en/html/net/release-notes/2024/aspose-html-for-net-24-10-release-notes.md, content/en/html/python-net/release-notes/2024/aspose-html-for-python-via-dotnet-24-10-release-notes.md
Prepared the Aspose.HTML 24.10.0 release notes
=> Prepared the Aspose.HTML 24.10.0 release notes

content/en/words/python/release-notes/2024/aspose-words-for-python-via-dotnet-24-11-release-notes.md
@MariiaGerasimova, please have a look.
FYI @aspose-evgeny-vasilev
=> Added release notes for Aspose.Words for Python via .Net 24.11.0

content/en/slides/java/release-notes/2024/aspose-slides-for-java-24-11-release-notes.md, content/en/slides/nodejs-java/release-notes/2024/aspose-slides-for-nodejs-via-java-24-11-release-notes.md
Aspose.Slides for Java/JasperReports/Android/PHP/Node.js/Python 24.11 Release Notes
=> Aspose.Slides for Java/JasperReports/Android/PHP/Node.js/Python 24.11 Release Notes

content/en/pdf/net/release-notes/2024/aspose-pdf-for-net-24-11-release-notes.md
Add Aspose.PDF for .NET 24.11 release notes
=> Add Aspose.PDF for .NET 24.11 release notes

content/en/slides/androidjava/release-notes/2024/aspose-slides-for-android-via-java-24-12-release-notes.md, content/en/slides/java/release-notes/2024/aspose-slides-for-java-24-12-release-notes.md, content/en/slides/nodejs-java/release-notes/2024/aspose-slides-for-nodejs-via-java-24-12-release-notes.md, content/en/slides/php-java/release-notes/2024/aspose-slides-for-php-via-java-24-12-release-notes.md
Aspose.Slides for Java/JasperReports/Android/PHP/Node.js/Python 24.12 Release Notes
=> Aspose.Slides for Java/JasperReports/Android/PHP/Node.js/Python 24.12 Release Notes

content/en/words/python/release-notes/2024/aspose-words-for-python-via-dotnet-24-12-release-notes.md
Added release notes for Aspose.Words for Python via .Net 24.12.0.
=> Added release notes for Aspose.Words for Python via .Net 24.12.0

content/en/pdf/net/release-notes/2024/aspose-pdf-for-net-24-12-release-notes.md
Add Aspose.PDF for .NET 24.12 release notes
=> Add Aspose.PDF for .NET 24.12 release notes

content/en/pdf/net/release-notes/2024/aspose-pdf-for-net-24-12-release-notes.md
Minor fix in aspose-pdf-for-net-24-12-release-notes
=> Minor fix in aspose-pdf-for-net-24-12-release-notes

content/en/words/python/release-notes/2025/_index.md, content/en/words/python/release-notes/2025/aspose-words-for-python-via-dotnet-25-1-release-notes.md
Added release notes for Aspose.Words for Python via .Net 25.1
=> Added release notes for Aspose.Words for Python via .Net 25.1

content/en/slides/java/release-notes/2025/_index.md, content/en/slides/java/release-notes/2025/aspose-slides-for-java-25-1-release-notes.md, content/en/slides/nodejs-java/release-notes/2025/_index.md, content/en/slides/nodejs-java/release-notes/2025/aspose-slides-for-nodejs-via-java-25-1-release-notes.md
Aspose.Slides for Java/JasperReports/Android/PHP/Node.js/Python 25.1 Release Notes
=> Aspose.Slides for Java/JasperReports/Android/PHP/Node.js/Python 25.1 Release Notes

content/en/zip/net/release-notes/2025/aspose-zip-for-net-25-1-release-notes.md
=> Release notes added for Aspose.ZIP for .NET 25.1.

content/en/html/net/release-notes/2025/_index.md, content/en/html/net/release-notes/2025/aspose-html-for-net-25-1-release-notes.md, content/en/html/python-net/release-notes/2025/_index.md, content/en/html/python-net/release-notes/2025/aspose-html-for-python-via-dotnet-25-1-release-notes.md
Prepared the Aspose.HTML 25.1 release notes
=> Prepared the Aspose.HTML 25.1 release notes

content/en/words/python/release-notes/2025/aspose-words-for-python-via-dotnet-25-2-release-notes.md
Added release notes for Aspose.Words for Python via .Net 25.2.0
=> Added release notes for Aspose.Words for Python via .Net 25.2.0

content/en/pdf/net/release-notes/2025/aspose-pdf-for-net-25-02-release-notes.md
Add Aspose.PDF for .NET 25.2 Release Notes.
=> Add Aspose.PDF for .NET 25.2 Release Notes.

content/en/pdf/net/release-notes/2025/aspose-pdf-for-net-25-02-release-notes.md
Minor fixes to PDFNET Release notes 25.2
=> Minor fixes to PDFNET Release notes 25.2

content/en/html/net/release-notes/2025/aspose-html-for-net-25-2-release-notes.md, content/en/html/python-net/release-notes/2025/aspose-html-for-python-via-dotnet-25-2-release-notes.md
Prepared the Aspose.HTML 25.2 release notes
=> Prepared the Aspose.HTML 25.2 release notes

content/en/html/net/release-notes/2025/aspose-html-for-net-25-3-release-notes.md, content/en/html/python-net/release-notes/2025/aspose-html-for-python-via-dotnet-25-3-release-notes.md
Prepared the Aspose.HTML 25.3 release notes
=> Prepared the Aspose.HTML 25.3 release notes

content/en/pdf/net/release-notes/2025/aspose-pdf-for-net-25-03-release-notes.md
Add Aspose.PDF for .NET 25.3 Release Notes.
=> Add Aspose.PDF for .NET 25.3 Release Notes.

content/en/slides/androidjava/release-notes/2025/_index.md, content/en/slides/androidjava/release-notes/2025/aspose-slides-for-android-via-java-25-3-release-notes.md, content/en/slides/java/release-notes/2025/aspose-slides-for-java-25-3-release-notes.md, content/en/slides/net/release-notes/2025/aspose-slides-for-net-25-3-release-notes.md, content/en/slides/nodejs-java/release-notes/2025/aspose-slides-for-nodejs-via-java-25-3-release-notes.md, content/en/slides/php-java/release-notes/2025/_index.md, content/en/slides/php-java/release-notes/2025/aspose-slides-for-php-via-java-25-3-release-notes.md
Aspose.Slides for Java/JasperReports/Android/PHP/Node.js/Python 25.3 Release Notes
=> Aspose.Slides for Java/JasperReports/Android/PHP/Node.js/Python 25.3 Release Notes

content/en/html/net/release-notes/2025/aspose-html-for-net-25-4-release-notes.md, content/en/html/python-net/release-notes/2025/aspose-html-for-python-via-dotnet-25-4-release-notes.md
Prepared the Aspose.HTML 25.4 releases notes.
=> Prepared the Aspose.HTML 25.4 releases notes.

content/en/words/python/release-notes/2025/aspose-words-for-python-via-dotnet-25-4-release-notes.md
@MariiaGerasimova, please have a look.
=> Added release notes for AW for Python 25.4

content/en/words/python/release-notes/2025/aspose-words-for-python-via-dotnet-25-5-release-notes.md
Added AW python 25.5 release notes
@MariiaGerasimova, please have a look.
FYI:  @aspose-evgeny-vasilev
=> AW python 25.5 release notes

content/en/html/net/release-notes/2025/aspose-html-for-net-25-5-release-notes.md, content/en/html/python-net/release-notes/2025/aspose-html-for-python-via-dotnet-25-5-release-notes.md
Prepared the Aspose.HTML 25.5 release notes
=> Prepared the Aspose.HTML 25.5 release notes

content/en/pdf/net/release-notes/2025/aspose-pdf-for-net-25-05-release-notes.md
Add Aspose.PDF for .NET 25.5 Release Notes.
=> Aspose.PDF for .NET 25.5 Release Notes.

content/en/slides/java/release-notes/2025/aspose-slides-for-java-25-5-release-notes.md, content/en/slides/nodejs-java/release-notes/2025/aspose-slides-for-nodejs-via-java-25-5-release-notes.md
Aspose.Slides for Java/JasperReports/Android/PHP/Node.js/Python 25.5 Release Notes
=> Aspose.Slides for Java/JasperReports/Android/PHP/Node.js/Python 25.5 Release Notes

content/en/words/python/release-notes/2025/aspose-words-for-python-via-dotnet-25-6-release-notes.md
@MariiaGerasimova, please have a look.
=> Added release notes for AW for Python 25.6

content/en/pdf/net/release-notes/2025/aspose-pdf-for-net-25-06-release-notes.md
Add Aspose.PDF for .NET 25.6 Release Notes.
=> Aspose.PDF for .NET 25.6 Release Notes.

content/en/pdf/net/release-notes/2025/aspose-pdf-for-net-25-06-1-release-notes.md
Aspose.PDF for .NET 25.6.1 Release Notes.
=> Aspose.PDF for .NET 25.6.1 Release Notes.

content/en/slides/java/release-notes/2025/aspose-slides-for-java-25-7-release-notes.md, content/en/slides/nodejs-java/release-notes/2025/aspose-slides-for-nodejs-via-java-25-7-release-notes.md
Aspose.Slides for Java/JasperReports/Android/PHP/Node.js/Python 25.7 Release Notes
=> Aspose.Slides for Java/JasperReports/Android/PHP/Node.js/Python 25.7 Release Notes

content/en/html/net/release-notes/2025/aspose-html-for-net-25-9-release-notes.md, content/en/html/python-net/release-notes/2025/aspose-html-for-python-via-dotnet-25-9-release-note.md
Prepared Aspose.HTML 25.9 release notes
=> Prepared Aspose.HTML 25.9 release notes
